### PR TITLE
Fix broken redirect after login

### PR DESCRIPTION
**Pull request by Kingminer7**
Fixed the broken redirect on the login page, although since I've never coded PHP I probably didn't use the absolute best method.

also yes i tested it

### CODE REVIEW

**Comment by MegaSa1nt** [comment]
Thank you for PR! I'll review my code and realize what it even does (cuz you did change, that can break something), so thanks!

**Comment by Kingminer7** [comment]
you know, i just found a way to do the same thing that is much easier.

so heres an explanation

so from, say, gdps.com/dashboard/login/login.php, you login and it redirects you to gdps.com/dashboard/dashboard.

what I did was make the login redirect to gdps.com/dashboard/

so here's your code with some comments from me
`if(isset($_SERVER['HTTPS']) && $_SERVER['HTTPS'] == 'on') $protocol = 'https://';` # seem to be checking if its https or not and setting protocol if so
        `else $protocol = 'http://';` # seems to be the or of the previous statement
`$path2 = $_SERVER["HTTP_HOST"].'/'; # It looks like you're grabbing the gdps.com url`
      	`$path = str_replace($procotol.''.$path2, '', $path); # honestly no idea whats happening here`
      	`$path = str_replace($protocol, '', $path); # no idea whats happening here either`
		`header('Location: ../'.$path); # and replacing the path here. already has the ../ so i dont know why you included $path`
	`}`

and here's my code

`header('Location: ../'); # simply sets the location to the folder above`

**Comment by MegaSa1nt** [comment]
Ok, thanks! I have no idea why this didnt worked first time

**Comment by Kingminer7** [comment]
alright!

**Pull request merged**
