### PR TITLE
Newgrounds soundtrack listen patch

### PR DESCRIPTION
**Pull request by masckmaster2007**
Allows to access direct link from reuploaded songs

image

### CODE REVIEW

**Comment by Xytriza** [comment]
> What about moving it in `music/handler.php` instead?

wouldn't work with how long GDPS urls are

**Comment by MegaSa1nt** [comment]
> Are you sure? `https://testgdps123.com/ngMusic.php?id=%i` `https://testgdps123.com/music/infos?id=%i`
> 
> Are the same length

what is music/infos

**Comment by Xytriza** [comment]
> > wouldn't work with how long GDPS urls are
> 
> Are you sure? `https://testgdps123.com/ngMusic.php?id=%i` `https://testgdps123.com/music/infos?id=%i`
> 
> Are the same length

true i guess

**Comment by MegaSa1nt** [comment]
Cool, will check a bit later

**Pull request merged**
