### PR TITLE
Added !cron command

### PR DESCRIPTION
**Pull request by OmgRod**
!cron in levels

i think this works

### CODE REVIEW

**Comment by Lila2048** [comment]
Question: is there a perm in the roles table you have to grant for this to work? Who can use it?

**Comment by OmgRod** [comment]
> Question: is there a perm in the roles table you have to grant for this to work? Who can use it?

anyone

**Comment by MegaSa1nt** [comment]
Dont really like the idea of using command lol, ill make it automatically a bit later

**Comment by MegaSa1nt** [comment]
Not approving, because commands are designed to interact with level, not whole server

**Pull request closed without merging**
