### PR TITLE
Announcements

### PR DESCRIPTION
**Pull request by Kingminer7**
# This pull is currently being redone. 
## Feel free to help with development - I'm busy now, and I've been working on other projects.
Adding an announcement system can be useful for some servers.

### CODE REVIEW

**Comment by Kingminer7** [comment]
aaaand i broke install.php

**Comment by MegaSa1nt** [comment]
Hi! Am i allowed to help you doing this thing?

**Comment by Kingminer7** [comment]
hey, any idea what's wrong with this?

`$check = $db->query("SHOW TABLES LIKE 'announcements'");
      	$exist = $check->fetchAll();
      	if(empty($exist)) { $db->query("CREATE TABLE `announcements` (
		 `userID` int(11) NOT NULL DEFAULT None,
		 `userName` varchar(50) CHARACTER SET utf8mb4 NOT NULL DEFAULT None,
		 `comment` longtext CHARACTER SET utf8mb4 NOT NULL,
		 `secret` varchar(10) CHARACTER SET utf8mb4 NOT NULL DEFAULT 'unused',
		 `commentID` int(11) NOT NULL DEFAULT None AUTO_INCREMENT,
		 `timestamp` int(11) NOT NULL DEFAULT None,
		 `likes` int(11) NOT NULL DEFAULT 0,
		 `isSpam` int(11) NOT NULL DEFAULT 0,
		 PRIMARY KEY (`commentID`)
		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"); 
		$db->query("ALTER TABLE `announcements` ADD INDEX(`userID`);");
		$db->query("ALTER TABLE `announcements` ADD INDEX(`timestamp`);");
		}`

**Comment by Kingminer7** [comment]
> Hi! Am i allowed to help you doing this thing?

oh yeah of course
im still newer to php and sql - luckily its similar to other coding languages and i'm a quick learner

**Comment by Kingminer7** [comment]
found it - had to do with defaults

**Comment by MegaSa1nt** [comment]
> hey, any idea what's wrong with this?
> 
> `$check = $db->query("SHOW TABLES LIKE 'announcements'");
>       	$exist = $check->fetchAll();
>       	if(empty($exist)) { $db->query("CREATE TABLE `announcements` (
> 		 `userID` int(11) NOT NULL DEFAULT None,
> 		 `userName` varchar(50) CHARACTER SET utf8mb4 NOT NULL DEFAULT None,
> 		 `comment` longtext CHARACTER SET utf8mb4 NOT NULL,
> 		 `secret` varchar(10) CHARACTER SET utf8mb4 NOT NULL DEFAULT 'unused',
> 		 `commentID` int(11) NOT NULL DEFAULT None AUTO_INCREMENT,
> 		 `timestamp` int(11) NOT NULL DEFAULT None,
> 		 `likes` int(11) NOT NULL DEFAULT 0,
> 		 `isSpam` int(11) NOT NULL DEFAULT 0,
> 		 PRIMARY KEY (`commentID`)
> 		) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci"); 
> 		$db->query("ALTER TABLE `announcements` ADD INDEX(`userID`);");
> 		$db->query("ALTER TABLE `announcements` ADD INDEX(`timestamp`);");
> 		}`

Dont do "null" by default, make '' pls

**Comment by Kingminer7** [comment]
> > hey, any idea what's wrong with this?
> > `$check = $db->query("SHOW TABLES LIKE 'announcements'"); $exist = $check->fetchAll(); if(empty($exist)) { $db->query("CREATE TABLE `announcements`(`userID`int(11) NOT NULL DEFAULT None,`userName`varchar(50) CHARACTER SET utf8mb4 NOT NULL DEFAULT None,`comment`longtext CHARACTER SET utf8mb4 NOT NULL,`secret`varchar(10) CHARACTER SET utf8mb4 NOT NULL DEFAULT 'unused',`commentID`int(11) NOT NULL DEFAULT None AUTO_INCREMENT,`timestamp`int(11) NOT NULL DEFAULT None,`likes`int(11) NOT NULL DEFAULT 0,`isSpam` int(11) NOT NULL DEFAULT 0, PRIMARY KEY (`commentID`) ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");  $db->query("ALTER TABLE `announcements` ADD INDEX(`userID`);"); $db->query("ALTER TABLE `announcements` ADD INDEX(`timestamp`);"); }`
> 
> Dont do "null" by default, make '' pls

just committed change

**Comment by Kingminer7** [comment]
i even tested it

**Comment by Kingminer7** [comment]
nope nvm

**Comment by Kingminer7** [comment]
so the basic server endpoints are ready, time to do the dashboard stuff

**Comment by Kingminer7** [comment]
hey - do you have a template or something for a page on dashboard?

**Comment by Kingminer7** [comment]
i give up for the night

**Comment by MegaSa1nt** [comment]
> hey - do you have a template or something for a page on dashboard?

yeah

**Comment by Kingminer7** [comment]
i realized i forgot the semicolon and fixed it locally but never committed to github - thanks

**Comment by Kingminer7** [comment]
i figured out the install issue wooooooo

**Comment by Kingminer7** [comment]
i dont know why but getGJAccountComments broke on my server - whether I install original dashboard or this fork of it. it seems https://gcs.icu/gcsdb/getGJAccountComments20.php works as expected (white screen) but https://gdps.km7dev.codes/g/getGJAccountComments20.php doesnt - unable to handle request.
even the cvolton repo doesnt.

**Comment by Kingminer7** [comment]
also gdps.km7dev.codes forwards to km7dev.000webhostapp.com - tried on 000webhost url, same result

**Comment by Kingminer7** [comment]
actually i think my server is just dead - the gd app broke.

**Comment by MegaSa1nt** [comment]
ini_set("display_errors", "On");
error_reporting(E_ALL);

**Comment by Kingminer7** [comment]
```
Warning: Undefined array key "accountID" in /storage/ssd4/813/20294813/public_html/g/incl/comments/getGJAccountComments.php on line 11

Warning: Undefined array key "page" in /storage/ssd4/813/20294813/public_html/g/incl/comments/getGJAccountComments.php on line 12

Fatal error: Uncaught TypeError: Unsupported operand types: string * int in /storage/ssd4/813/20294813/public_html/g/incl/comments/getGJAccountComments.php:13 Stack trace: #0 /storage/ssd4/813/20294813/public_html/g/getGJAccountComments20.php(2): include() #1 {main} thrown in /storage/ssd4/813/20294813/public_html/g/incl/comments/getGJAccountComments.php on line 13
```

**Comment by Kingminer7** [comment]
maybe its because its web, but gcs.icu doesnt have that problem - odd.

**Comment by MegaSa1nt** [comment]
> maybe its because its web, but gcs.icu doesnt have that problem - odd.

see 3 error

**Comment by Kingminer7** [comment]
i think $page is a string somehow.
`$commentpage = $page*10;`

**Comment by Kingminer7** [comment]
in game it works fine - using gdhm gdps switcher
on green cats server it pulls up white page on browser but on mine it pulls up the error
not sure why

**Comment by Kingminer7** [comment]
Hey, do you think announcements should sort by time or id? Usually should go together

**Comment by Kingminer7** [comment]
ah dang it likes and timestamps are labeled wrong

**Comment by MegaSa1nt** [comment]
There is $dl->convertToDate(); function, i recommend using it

**Comment by Kingminer7** [comment]
likes are not accessible on dashboard, possibly will add. only reason its not added is liking/disliking multiple times!

**Comment by Kingminer7** [comment]
i finally got it working, so its no longer a draft.

**Comment by Kingminer7** [comment]
now the most recent announcements appear on top.

also, i started this project yesterday with very little php knowledge, but with your help i got through this project.

**Comment by MegaSa1nt** [comment]
i will check that after i upload big update, ok?

**Comment by MegaSa1nt** [comment]
will it be OK, if i rework it? (just announcements view page)

**Comment by Kingminer7** [comment]
> will it be OK, if i rework it? (just announcements view page)

Yeah, of course!
I just copied the song and level views because I'm newer to pho

**Comment by MegaSa1nt** [comment]
its ok

**Comment by Kingminer7** [comment]
hey megasa1nt - any idea why i can't merge your newest commits to my fork? all it says is `This branch has conflicts that must be resolved` but doesnt tell me what conflicts.

**Comment by MegaSa1nt** [comment]
Hmm, strange

**Comment by Kingminer7** [comment]
ok after i manually updated dashboard lib it tells me that install.php has conflicts

**Comment by Kingminer7** [comment]
ohh its the favorite songs part of install.php

**Comment by Kingminer7** [comment]
ight think i got it

**Comment by MegaSa1nt** [comment]
I changed "isSpam" to "picture"

**Comment by MegaSa1nt** [comment]
What about Markdown support?

**Comment by Kingminer7** [comment]
i like those ideas, also kept isSpam just in case it was needed

**Comment by MegaSa1nt** [comment]
I dont think, that announcement will be marked as spam

**Comment by Kingminer7** [comment]
> I dont think, that announcement will be marked as spam

yeah I kept it for gd itself, but now I realize that won't even be needed

**Comment by Kingminer7** [comment]
hey @MegaSa1nt, could you add the md/picture to this or create a pr?

**Comment by MegaSa1nt** [comment]
> hey @MegaSa1nt, could you add the md/picture modifications to this or create a pr?

Oh, i forgot about this PR, sorry
I'll make commits to this when i come back

**Comment by Kingminer7** [comment]
its fine, i did too (mainly because ive been busy lately)

**Comment by Kingminer7** [comment]
this pull is broken now, at this point i may just redo it.

**Comment by Kingminer7** [comment]
I decided to move the Announcements button to Browse and the Create Announcement button is in the Mod Tools again.
I grabbed the "Not finished yet" page from when this pull was originally made and I'm currently using it on both pages.

**Comment by Kingminer7** [comment]
image
Still much to be done, but it's getting closer.

**Comment by Kingminer7** [comment]
gotten it neatened since last comment and started the create page, although it doesn't work yet.
image
![image](https://github.com/MegaSa1nt/GMDprivateServer/assets/100500023/3ea053aa-b98f-4991-a94c-8d6017b8c583]

**Comment by Kingminer7** [comment]
file uploading is annoying.
also new value in dashboard.php

**Comment by MegaSa1nt** [comment]
Idk, if this is needed tbh, every GDPS has Discord server, which is better in news part
I'm closing this for now, if you still want to finish this, ask me to open it

**Pull request closed without merging**
