### PR TITLE
Event levels!

### PR DESCRIPTION
**Pull request by thejulfor**
Important ❗
You have to download Geode mod ["Event Levels" by TimeStepYT](https://geode-sdk.org/mods/timestepyt.eventlevels)
to be able to open and view event levels in main menu.

image

❗ Also, after installation go to mod settings and disable "Modified Daily Page" otherwise you will see regular daily level in the event level page.

image

For this to work I decided to create separate table in the database specifically for event levels.
Why? Because we don't know how long event levels should last. 1 week? 1 month? 3 months?

There is currently no tool or webpage to add event levels so you have to add them manually in the database.

**'events' table:**
feaID (int) - unique id of event level
levelID (int) - level id
timestamp (int) - unix timestamp, when the event level should start
duration (int) - event duration in seconds until it is not able to be played anymore
webhookSent (int) - does nothing currently, added for consistency with dailyFeatures table

### CODE REVIEW

**Comment by thejulfor** [comment]
да хуй знает мне так показалось лучше

**Comment by MegaSa1nt** [comment]
не

**Comment by thejulfor** [comment]
gandon

**Comment by MegaSa1nt** [comment]
loh

**Comment by MegaSa1nt** [comment]
возможно, идея с новой таблицей не такая уж и плохая

**Comment by MegaSa1nt** [comment]
а я зачем открыл, я переделаю немного

**Pull request closed without merging**
