### PR TITLE
2.2 dashboard

### PR DESCRIPTION
**Pull request by MegaSa1nt**
will merge when Cvolton merges `lists` branch on OG GMDPrivateServer

### CODE REVIEW

**Comment by OmriOn** [comment]
cmon merge!!

**Comment by MegaSa1nt** [comment]
> cmon merge!!

> will merge when Cvolton merges lists branch on OG GMDPrivateServer

**Comment by Neejik** [comment]
is there a way to add the changes made in this PR even if you don't merge?

**Comment by Uproxide** [comment]
add mods page didnt work :(

**Comment by MegaSa1nt** [comment]
are you sure you updated all files?

**Comment by MegaSa1nt** [comment]
even https://github.com/MegaSa1nt/GMDprivateServer/blob/listscopy/dashboard/account/mods.php ?

**Comment by Uproxide** [comment]
yes

**Comment by CustomGameGD** [comment]
image

**Pull request merged**
