### PR TITLE
fix timestamps

### PR DESCRIPTION
**Pull request by Xytrizareal**
formatted timestamps to be like gd

### CODE REVIEW

**Comment by MegaSa1nt** [comment]
There is `makeTime()` function doing same + https://github.com/Cvolton/GMDprivateServer/pull/900

Thanks for PR tho, will use it as sample for dashboard-like time

**Comment by Xytrizareal** [comment]
just realized that gd includes "ago" at the end anyways ill fix it lmao

**Comment by Xytrizareal** [comment]
fixed

**Comment by MegaSa1nt** [comment]
image
Offtop: if you use this to disable link song reupload, then you can disable it in config/dashboard.php

**Comment by Xytrizareal** [comment]
i did notice lmao dw

**Comment by Xytrizareal** [comment]
i just didnt use my time ass brain

**Comment by Xytrizareal** [comment]
i have no idea how to make one commit for all of these, sorry for  the multiple commits if ur gonna accept the pr 💀

**Comment by MegaSa1nt** [comment]
idc, but you can use GitHub Desktop for editing multiple files to one commit

**Comment by Xytrizareal** [comment]
oh ok

also i fucked up my repo by accident LMAO

**Comment by Xytrizareal** [comment]
i tried to fix it

**Pull request closed without merging**
