### PR TITLE
Small fix

### PR DESCRIPTION
**Pull request by Fenix668**

### CODE REVIEW

**Comment by MegaSa1nt** [comment]
Remove "timezone fix", please, this was made on purpose

**Comment by Fenix668** [comment]
I should have taken it off

**Comment by MegaSa1nt** [comment]
Woah

**Comment by MegaSa1nt** [comment]
You deleted file

**Comment by Fenix668** [comment]
I actually didn't want it to be deleted in the commit, I just wanted to leave "README.md" without including the other commit. Maybe you change it

**Pull request closed without merging**
