### PR TITLE
Improvements on translations

### PR DESCRIPTION
**Pull request by jerosajose**
First 132 lines of the Spanish file were revised. I'll do the rest when I find some time (I need to study for exams lmaon't).

Some things I wanted to comment:
* Don't abuse of exclamation marks, at least in Spanish, it reduces their importance.
* Also be careful with calling things by two ways on the same language (username -> whether "apodo" or "nombre de usuario"; but not both)
* I might need context for some strings, are they have many ways to be translated, but it depends of who does the action, the action itself, etc.

But very good overall

### CODE REVIEW

**Comment by MegaSa1nt** [comment]
Nice, thank you! Will merge when is ready ig

**Comment by Ascript89** [comment]
Lol thanks for crediting me, I didn't notice that in the files xd

**Comment by MegaSa1nt** [comment]
You can get some context on my GDPS, it has Spanish set: https://gcs.icu/

**Comment by MegaSa1nt** [comment]
There is a few new lines :trollface:

**Comment by Neejik** [comment]
https://github.com/Ascript89/GMDprivateServer/pull/1
Hey @Ascript89 (sorry the ping), you should check out my new version with your improvements

Any feedback in there is welcome so you could merge my PR
[Also test it from my dashboard](https://gdunnamed.000webhostapp.com/dashboard/)

**Comment by Xytriza** [comment]
> [Ascript89#1](https://github.com/Ascript89/GMDprivateServer/pull/1) Hey @Ascript89 (sorry the ping), you should check out my new version with your improvements
> 
> Any feedback in there is welcome so you could merge my PR [Also test it from my dashboard](https://gdunnamed.000webhostapp.com/dashboard/)

pings in github 👍

**Comment by Ascript89** [comment]
> > [Ascript89#1](https://github.com/Ascript89/GMDprivateServer/pull/1) Hey @Ascript89 (sorry the ping), you should check out my new version with your improvements
> > 
> > Any feedback in there is welcome so you could merge my PR [Also test it from my dashboard](https://gdunnamed.000webhostapp.com/dashboard/)
> 
> pings in github 👍 

?

**Comment by MegaSa1nt** [comment]
I don't think it's very important, but if you want to finish this, reopen pull request

**Comment by jerosajose** [comment]
Yikes lol

**Pull request closed without merging**
