### PR TITLE
fix grammar with "Noone" as it should be "No one"

### PR DESCRIPTION
**Pull request by Xytrizareal**
:trollface:

### CODE REVIEW

**Comment by MegaSa1nt** [comment]
What about other grammar issues? It would be cool!

**Comment by Xytrizareal** [comment]
im native english so ill just go thru it, sure

**Comment by Xytrizareal** [comment]
havent read it all but from like <lastline> - 450 seems fine to me so far

**Comment by MegaSa1nt** [comment]
No other grammar issues? I think i saw some, but i don't remember where

**Pull request closed without merging**
