### PR TITLE
Clan tags

### PR DESCRIPTION
**Pull request by thejulfor**
Added clan tags, visible in dashboard and in game

### CODE REVIEW

**Comment by Xytrizareal** [comment]
hey, that makeTime thing looks very similar to mine....

**Comment by Xytrizareal** [comment]
i sure wonder why that is

**Comment by Xytrizareal** [comment]
and now its changed 🙃

**Comment by MegaSa1nt** [comment]
> hey, that makeTime thing looks very similar to mine....

we're in VC rn

**Comment by Xytrizareal** [comment]
i'm just joking i don't mind lmao

**Comment by MegaSa1nt** [comment]
ik, dw

**Comment by Xytrizareal** [comment]
unrelated to this, when i click a lot of stuff in the dashboard why does it always show an X in the bottom right

**Comment by MegaSa1nt** [comment]
> unrelated to this, when i click a lot of stuff in the dashboard why does it always show an X in the bottom right

you're using Nginx, dashboard relies on htaccess from Apache

**Comment by Xytrizareal** [comment]
oh 😭

**Comment by Xytrizareal** [comment]
will ya ever add nginx support

**Comment by Xytrizareal** [comment]
i forgot if u said u we're going to

**Comment by MegaSa1nt** [comment]
i will, but later

**Comment by Xytrizareal** [comment]
@MegaSa1nt whats ur discord tag btw

**Comment by MegaSa1nt** [comment]
МегаСвятой#9096

**Pull request merged**
