### PR TITLE
validate comments (level must exist)

### PR DESCRIPTION
**Pull request by Xytriza**

### CODE REVIEW

**Comment by Xytriza** [comment]
tested it btw

**Comment by Xytriza** [comment]
@MegaSa1nt

**Comment by MegaSa1nt** [comment]
https://github.com/MegaSa1nt/GMDprivateServer/pull/114#pullrequestreview-2051176876

**Comment by Xytriza** [comment]
what

**Comment by Xytriza** [comment]
whats a review

**Comment by Xytriza** [comment]
> 

but its pointless and a bug

**Comment by Xytriza** [comment]
should i REALLY do that shitty "feature" back?

**Comment by MegaSa1nt** [comment]
Yes?? Its one line and not a but lol

**Comment by Xytriza** [comment]
> Yes?? Its one line and not a but lol

its stupid but FINE
godi feel like im in a fight with my mom lmao

**Comment by MegaSa1nt** [comment]
Dont forget to do your homework after

**Comment by Xytriza** [comment]
i forgor about this ill do it now 👍 
also fuck homework 👍 👍 👍

**Comment by Xytriza** [comment]
god i am way too bored

**Comment by MegaSa1nt** [comment]
Lol

**Comment by Xytriza** [comment]
@MegaSa1nt merGE?

**Comment by MegaSa1nt** [comment]
Sorry, when I'll test it, ~13-14 hours

**Comment by Xytriza** [comment]
ok  svvvvvvdsvvvvvvdassvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvassvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv

**Pull request merged**
