### PR TITLE
timestamp fix

### PR DESCRIPTION
**Pull request by Xytrizareal**
i did the timestmaps like robtop did in original gd

(remade pr because i made so many commits and fucked up the old branch xD)

### CODE REVIEW

**Comment by MegaSa1nt** [comment]
do you allow me to change your PR?

**Comment by Xytrizareal** [comment]
yeah

**Comment by Xytrizareal** [comment]
you should have the Allow edits by maintainers thing

**Comment by MegaSa1nt** [comment]
Added as #61, will include you as one of contributors, thanks!

**Comment by Xytrizareal** [comment]
ok ty

**Pull request closed without merging**
