### PR TITLE
Cloudflare proxy check

### PR DESCRIPTION
**Pull request by M336G**
Adds a setting to only allow requests coming from Cloudflare IPs

- Update the IP ranges and add support for IPV6 in the isCloudflareIP function (incl/lib/mainLib.php)
- Add the isCloudflareIP function (incl/lib/ipCheck.php)
- Add the cloudflareProxy setting (config/security.php)
- Add credits to the Cloudflare IPs list (README.md)

### CODE REVIEW

**Comment by Xytriza** [comment]
i don't see this as useful or understand what the point is?

**Comment by Xytriza** [comment]
also maybe change https://www.cloudflare.com/fr-fr/ips to https://www.cloudflare.com/ips, it should auto do the language

**Comment by Xytriza** [comment]
^ if for some reason this gets accepted

**Comment by MegaSa1nt** [comment]
> i don't see this as useful or understand what the point is?

I see. If you proxy your GDPS through Cloudflare, main server will get requests only from Cloudflare IPs, it means we can check if IP is Cloudflare one
If you somehow leaked your real GDPS IP, it could help to prevent avoiding Cloudflare security

**Pull request closed without merging**
