### PR TITLE
Add default colors to the rate webhook on difficulties in setColor

### PR DESCRIPTION
**Pull request by Fenix668**
Small preview to have the "setColor" of the webhook rate default to the color of the level difficulty.

### CODE REVIEW

**Comment by MegaSa1nt** [comment]
Cool, but what about making it configurable if someone doesn't want it?

**Comment by Fenix668** [comment]
At the moment, I tried to integrate the functionality in discord.php to enable the default color for difficulties. This feature functions properly when setting "$originalDiffColor" to "true". However, it only applies when $successColor is left empty; otherwise, it adopts the color value specified in $successColor.

https://github.com/MegaSa1nt/GMDprivateServer/commit/56cf9ce843ed8c5f47cc53bdd87d273ac45e8daa

**Comment by Xytriza** [comment]
yeah i wouldn't want this at all just saying in my opinion

> Cool, but what about making it configurable if someone doesn't want it?

**Comment by Xytriza** [comment]
i like normal colors

**Comment by Fenix668** [comment]
> i like normal colors

One thing could be done. Let's make the value of $originalDiffColor automatically enabled when a person has already chosen the color for the webhook from successColor, otherwise if they want the already automated one they leave successColor empty. If the idea goes well, I remove $originalDiffColor on /config/discord.php and leave it in mainLib.php, so for those who want the color from $successColor, the webhook will take the value of that color, otherwise if someone doesn't want it, they leave it empty and the webhook takes that of $originalDiffColor

**Comment by Xytriza** [comment]
i like my normal stuff the way it is imo

**Comment by Fenix668** [comment]
> i like my normal stuff the way it is imo

Well it depends, maybe someone will apply the color of the webhook based on the difficulty. For now I have left it normal, if someone would like to have the colors of the difficulties, they will leave the value of $successColor empty

**Pull request merged**
